### ISSUE TITLE
Cave MRAs

### ISSUE THREAD

**Issue by nullobject** [MiSTer-devel/MRA-Alternatives_MiSTer#34]
Hi :wave:

I appreciate folks helping out with the Cave MRAs, but I don't think that the Japanese versions of the games belong in the alternatives repo.

If you ask most fans of Cave games, usually the Japanese releases are the ones they like to play. For this reason I want to keep all official Cave releases (both English and Japanese) in the main Cave repo. IMHO it's only ROM hacks and bootlegs that should end up in here.

What do you think?

/cc @thehughhefner

**Comment by thehughhefner** [comment]
That sounds absolutely fair. The reason why I added them to the alternative folder was because of trying to keep it simillar to other mra files, where one "main" version would be in the _Arcade folder. 
I will make the changes according to what you wrote @nullobject :)

**Comment by nullobject** [comment]
@thehughhefner It's hard to keep everyone happy. But I know for a fact if I start moving the Japanese MRAs into the alternatives folder, some people are going to freak out 🙀

Let's start with the the bootlegs/ROM hacks and go from there :smile:

**Comment by thehughhefner** [comment]
Yes! Pull request incoming :) Thanks for the feedback

**Comment by theypsilon** [comment]
I merged the PR, thanks!

If the JP version is the most important, I'd consider to have it as the main one, and then moving the english MRA to alternatives. What do you think @nullobject ?

**Comment by nullobject** [comment]
@theypsilon Hey buddy, sorry I've been away for work for the week.

It's a good idea, I'll run it past a couple of my patrons and get a little feedback.

While the core is still under active development, I'm quite happy to have all the MRAs together. But I will definitely be looking to split things up once it gets more stable.

Closing this issue.
