### ISSUE TITLE
1942 Supercharger + C64 Music - HBMame

### ISSUE THREAD

**Issue by MJY71** [MiSTer-devel/MRA-Alternatives_MiSTer#4]
The rbf tag 1942 should be changed to jt1942

**Comment by eubrunosilva** [comment]
hi.
no because this alternatives are only for official cores.
1942 in original repo is 1942 and not jt1942

**Comment by MAME-GETTER** [comment]
It's broken and does not work.

**Comment by MJY71** [comment]
Ahh, okay. My apologies.

**Comment by theypsilon** [comment]
It seems this MRA was removed from here.
