### ISSUE TITLE
Donkey Kong Alternatives not working

### ISSUE THREAD

**Issue by evidencedj** [MiSTer-devel/MRA-Alternatives_MiSTer#5]
Since the new version of Donkey Kong 20210112 most of the alternatives are not working anymore. I only get yellow ish graphics. 
When I fallback to Version 20200108 these alternatives run fine. A friend of mine has the same problem. The mame and hbmame roms are from update_all.

![20210205_162433](https://user-images.githubusercontent.com/33894818/107054478-7644a200-67d0-11eb-86db-7ec7ffddd1b6.jpg)

**Comment by eubrunosilva** [comment]
hi.
yes i'm sorry. I need to review all cores and alternatives and release a new pack.
i cannot give an eta but i will start soon

**Comment by jstavats** [comment]
I was able to fix the rainbow donkey kong.mra by updating the rom layout in the mra to better match what is in the new donkey kong.mra. It looks like they’ve changed where things are duplicated and found...

**Comment by jstavats** [comment]
A pull request put in with fixes for this. All the Donkey Kong mra's in the file are updated and seem to work.  The MD5's in them were left set to "none".

**Comment by theypsilon** [comment]
This issue should be solved with this merged PR: https://github.com/MiSTer-devel/MRA-Alternatives_MiSTer/pull/6
